.gitignore
I checked out caprica locally, and following the [Quick-start] (https://github.com/google/capirca/wiki/Quick-start) guide I generated the filters with `./aclgen.py`.  This added a number of untracked files to the repo:
```
filters/sample_cisco_lab.acl
filters/sample_gce.gce
filters/sample_ipset
... etc ...
... a number of .pyc files ...
```
This PR hides those to keep the working directory clean.
If this isn't the preferred way of dealing with this (i.e., if you would prefer that developers have their own personal .gitignore file), I can submit a separate PR with instructions to the README or wherever is appropriate.
=> Add .gitignore for generated filter/sample files and .pyc

requirements.txt
On a fresh install (or using virtualenv), `definate.py` currently fails:
```
$ ./definate.py 
Traceback (most recent call last):
File "./definate.py", line 29, in <module>
import yaml
ImportError: No module named yaml
```
This is fixed with `sudo pip install PyYAML`.  I've added a `requirements.txt` so users can install the needed dependencies with `$ pip install -r requirements.txt`.
I tried to add pyyaml to setup.py, but got a warning:  `/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'`.  I didn't want to change setup.py further (i.e., change from distutils.core to setuptools), as that seemed invasive.
=> Add pyyaml, required for definate.py.

aclgen.py, test/test_aclgen.py
This is a preparatory PR that should let us add characterization tests to the existing code.  It adds some simple smoke tests to `aclgen.py`, generating to the existing project folders.  The output is _not_ checked, these are smoke tests only.
The tests can be run from the project root dir with `$ python -m unittest discover`.
If/when this PR is accepted, I can add some very simple characterization tests, which would consist of running acl with the existing committed data, storing the output, and using that as the basis for test assertions, which would allow for work on the code without breaking anything.
**Summary of code changes:**
* `main()` parameterized to `main(array_of_args)` so unit tests can pass in different arg lists.
* Added `test` folder to keep this distinct from `tests` …
=> Add aclgen smoketests

tests/characterization_data/filters_expected/sample_cisco_lab.acl, tests/characterization_data/filters_expected/sample_multitarget.acl, tests/characterization_data/filters_expected/sample_multitarget.bacl, tests/characterization_data/filters_expected/sample_multitarget.eacl, tests/characterization_data/filters_expected/sample_multitarget.xacl
fix MOE_MIGRATED_REVID=131342769, it broke all characterization tests that utilized the cisco.py platfrom generator.
=> fix broken characterization tests

tests/lib/nsxv_unittest.py
Summary:
The nsxv unittest was referencing a text address family
attribute that seems to be Cisco-specific, which is not implemented by
this platform.
Test Plan:
ran all test*.py modules in tests/ directory and saw this
passed.
=> Fix nsxv unittest

lib/iptables.py
The conntrack module for ICMPv6 only supports NEW states for type 128 and 139.
Using the state module for e.g. 135 will prevent the rule from matching and
results in a not working ND.
Signed-off-by: Florian Zavatzki fz@binsec.com
=> Disable state module for most ICMPv6 types

lib/juniper.py, lib/policy.py, lib/srxlo.py, tests/lib/juniper_test.py
Starting in JUNOS 14, Trio line cards for MX routers now support 'flexible match' which is a very powerful DPI-like capability that allows you to match on a packets' headers or content using byte & bit offsets and hex or binary patterns. This can then be used to combat known attack signatures on a router at near line-rate.
This PR is specific to flexible-match-range; I will probably get working on the other flexible match variant (flexible-match-mask) later this month.
Usage example:
```
term flex-match-term-1 {
protocol:: tcp
flexible-match-range:: bit-length 8
flexible-match-range:: range 0x08
flexible-match-range:: match-start payload
flexible-match-range:: byte-offset 16
flexible-match-range:: bit-offset 7
action:: deny
}
```
=> add flexible-match-range functionality to juniper platform

requirements.txt
* After patch 0ae35f5 newer python-gflags now required,
otherwise you will encounter "gflags.FlagsError: Flag name must be a
string"
Signed-off-by: Misha Komarovskiy <zombah@gmail.com>
=> requirements: Use python-gflags 3.0 or higher

doc/policy_format.txt, lib/nsxv.py, policies/pol/sample_nsxv.pol, tests/lib/nsxv_test.py
The header options for the nsx policy will support securitygroup securitygroup-id as the target options. These are optional. If these target options are given, all the rules in the section will have appliedTo as the given Security Group.
If the values are not given, the appliedTo will be default to DISTRIBUTED_FIREWALL
=> Nsxv plugin Enhancements

lib/junipersrx.py, tests/README, tests/lib/junipersrx_test.py
Fix issue where source-exclude and destination-exclude keywords 
generated unexpected output of null address book names.  In addition, 
the use of a naked *-exclude raised errors.
This change leverages the term name to create an address-book name
for the IPs resulting from excluding source or destinations.
Appropriate unit tests are also included.
Added a README in ./tests/ for reference.
=> Fix source-exclude/destination-exclude keywords in SRX generator

lib/summarizer.py, tests/lib/summarizer_test.py
The module **summarizer.py** has a bug in the procedure **_SummarizeSameMask**. This procedure is used for the summarization of non contiguous subnet masks. During the summarization, the networks are sorted (after converting from "dot formatted" to integer) and then they are iterated several times to summarize them. But there is an issue when this summarization is done over a network already summarized in more than one octet. If two octets were already summarized the algorithm is failing because it's not taken into consideration the network mask after finding those networks are contiguous. This is the fix provided.
You can reproduce the issue if you create a simple policy file with only one term and only one object as source or destination and the following IPs inside NETWORK definition …
=> Fix for DSMO issue

capirca/lib/cisco.py, tests/lib/arista_test.py, tests/lib/brocade_test.py, tests/lib/cisco_test.py, tests/lib/ciscoxr_test.py
Cisco ACL allows to handle specifically fragments adding the keyword "fragments" to the end of any L3 ACE. This PR will allow that through the use of "fragments" as an option in Capirca policy.
=> Fragments support in Cisco

capirca/aclgen.py
Trying to run aclgen with --debug or --verbose would fail with "AttributeError: 'module' object has no attribute 'basicConfig'"
Changing logging.basicConfig calls to use absl's logging.set_verbosity instead fixed the issue
(this is just a clean recreation of closed request #165 )
=> Changed logging.basicConfig calls to logging.set_verbosity to work with absl logging

capirca/lib/cisco.py, capirca/lib/ciscoasa.py
Specifically, replaced TermPortToProtocol (which had Cisco mappings
defined inside it) with PortMap class that defines both sets of mappings
and provides function to look up service name based on port + platform
=> Addresses issue #166: Separating Cisco port/service name mappings from Arista ones

.travis.yml, capirca/lib/ciscoasa.py, setup.py, tests/lib/aclcheck_test.py, tests/lib/aclgenerator_test.py, tests/lib/cisco_test.py, tests/lib/ciscoxr_test.py, tests/lib/cloudarmor_test.py, tests/lib/gce_test.py, tests/lib/gcp_hf_test.py, tests/lib/ipset_test.py, tests/lib/iptables_test.py, tests/lib/juniper_test.py, tests/lib/junipersrx_test.py, tests/lib/nacaddr_test.py, tests/lib/naming_test.py, tests/lib/nftables_test.py, tests/lib/nsxv_functtest.py, tests/lib/nsxv_test.py, tests/lib/nsxv_unittest.py, tests/lib/packetfilter_test.py, tests/lib/paloaltofw_test.py, tests/lib/policy_simple_test.py, tests/lib/policy_test.py, tests/lib/srxlo_test.py, tests/lib/summarizer_test.py, tests/lib/windows_advfirewall_test.py, tests/lib/windows_test.py
To avoid having PRs refused because they do not pass the whitespace check at the copybara step, adding it to the travis step will allow early reporting of invalid PRs.
To also make sure that the current project doesn't fail those checks, autopep8 was used to fix some linting issues. The commands used were:
```bash
$ autopep8 --ignore E226,E24,W50,W690,E111,E114,W191,E101 --max-line-length 100 --in-place --aggressive --aggressive --recursive capirca
$ autopep8 --ignore E226,E24,W50,W690,E111,E114,W191,E101 --max-line-length 100 --in-place --aggressive --aggressive --recursive tests
```
=> Added travis tests that ensure whitespace will fail the PR check

capirca/lib/naming.py
Used context manager to ensure that files are closed appropriately in the `capirca.lib.naming` module
fixes #196
=> Ensured file handlers are closed appropriately in capirca.lib.naming

.travis.yml, capirca/lib/aclgenerator.py, requirements.txt, test-requirements.txt, tests/lib/aclgenerator_test.py, tests/unit/wrapwords_test.py
From @ankenyr :
"There is a hard line limit on certain platforms which is what the method WrapWord tries to fix. Currently the regular expression will break on whitespace. It however fails if a single "word" is over the limit. This ACL would be invalid and result in an error if you tried to apply it to a machine.
Instead I would expect it to try and break on whitespace but if it cannot and a single "word" exceeds the max character, force the break at the max"
=> Fixed issue with WrapWords not breaking text with no spaces

capirca/lib/nacaddr.py
A lot of time is spent recreating the IP objects when performing address list exclusion. By extracting the IP integer and prefixlen from the object, we can use the parent constructor more efficiently (since this tuple is the fastest way of creating the IP network object in `ipaddress`).
This could instead be done by just copying the parameters to the internal instead, which would be a 4x performance boost (according to `timeit`), but as it stands this is already a significant boost.
```python
>>> import ipaddress
>>> class IPv4(ipaddress.IPv4Network):
...     def __init__(self, ip_str):
...             if isinstance(ip_str, ipaddress._BaseNetwork):
...                     self.network_address = ip_str.network_address
...                     self._prefixlen = ip_str._prefixlen
... …
```
=> chg: faster creation/copying of IP objects when they receive an IP object constructor

capirca/aclgen.py, setup.py
When `max_renderers` is set to 1, only a single thread will be running anyways and we can forego the overhead of the multiprocessing pool. Plus, cProfile doesn't play nicely with multiprocessed applications and fails due to a pickling error.
=> Added single-threaded logic

README.md, capirca/aclgen.py, capirca/utils/config.py, requirements.txt, setup.py, tests/integration/aclgen_test.py
Allow the usage of YAML files to configure `aclgen` for Capirca.
Despite the default being stripped from the CLI definition and inserted into the description, there should be no difference between the previous `aclgen --helpfull` to the one that implements this pull request. This is because all config defaults have now been moved to `capirca.utils.config`. Changes to the defaults in that module will translate to changes in the default flags.
=> new: added file-base configuration for capirca

capirca/aclgen.py
Due to the way that multiprocessing now starts processes, FLAGS is not reachable in RenderFile().
This causes (on OS X under Python 3.9 at least) :
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/Users/wkumari/src/github/wkumari-caprica/capirca/aclgen.py", line 213, in RenderFile
conf, definitions, optimize=FLAGS.optimize,
File "/usr/local/lib/python3.9/site-packages/absl/flags/_flagvalues.py", line 480, in __getattr__
raise AttributeError(name)
AttributeError: optimize
"""
```
This seems to be a result of the addition of, and change to using `spawn` as default start …
=> Make FLAGS (optimize, shade_check) available to Run() in MP

capirca/lib/paloaltofw.py
Functionally equivalent to previous with exceptions:
remove XML declaration as not needed
change config version to 8.1.0 (earliest supported PAN-OS)
don't indent XML as this can be performed with other tooling
(e.g., xmllint)
application groups are not currently used and the XML was
not rendered correctly, so remove XML generation for now.
=> Convert hand rolled XML document generation to use the ElementTree module.

policies/pol/sample_paloalto.pol
The sample result can now be loaded on a firewall.
=> http is not a valid PAN-OS application; replace with web-browsing.

capirca/lib/paloaltofw.py, tests/lib/paloaltofw_test.py
Expose ElementTree config root in paloaltofw.PaloAltoFW() as a data
attribute.
Use it in the unittests to replace string matching in the XML (assertIn()
and assertNotIn()).  This results in more accurate verification of tests
using ElementTree's XPath expression support.
=> Rework PAN-OS unittests to use ElementTree.

capirca/lib/paloaltofw.py, tests/lib/paloaltofw_test.py
These fields are already truncated at maximum length.
Add unittests for:
1) maximum length
2) maximum length + 1
3) verify warning logs for maximum length + 1
=> Log warning when PAN-OS tag comments or rule description length exceeded.

tests/lib/paloaltofw_test.py
1. maximum length
2. maximum length + 1
=> Add unittests for maximum PAN-OS rules name length.

capirca/lib/paloaltofw.py, tests/lib/paloaltofw_test.py
If source-port is specified add it to a service object.  If there is
no destination-port then add range 0-65535 to the service destination
port because it is required field.  The port range is used vs. "any"
due to recent changes which disallow any in the WebUI.
=> PAN-OS: Enhancement to handle term source-port keyword.

capirca/lib/paloaltofw.py, tests/lib/paloaltofw_test.py
If no source-port and destination-port and protocol contains tcp or
udp create (one time) service any-tcp or -any-udp and specify in
service.
=> PAN-OS: Enhancement to handle tcp or udp with no ports specified.

capirca/lib/paloaltofw.py, tests/lib/paloaltofw_test.py
Add unit tests for check above, and invalid ICMP type.
Background: this check was previously handled in
aclgenerator.Term.NormalizeIcmpTypes(), and the function call was
removed.  NormalizeIcmpTypes() is not address family "mixed" aware, so
just added the missing check needed.  And the local Term() class is
no longer needed, so remove it.
=> Add check for ICMP types used with non-ICMP protocols.

capirca/lib/paloaltofw.py, doc/generators/paloaltofw.md, tests/lib/paloaltofw_test.py
address objects: specifies whether custom address objects or
network/mask definitions are used in security policy source and
destination fields
addr-obj: specifies address groups are used in the security policy
source and destination fields (default)
no-addr-obj: specifies network/mask definitions are used in the
security policy source and destination fields
=> PAN-OS: Add "address objects" header option.

capirca/lib/paloaltofw.py, doc/generators/paloaltofw.md, policies/pol/sample_paloalto.pol, tests/lib/paloaltofw_test.py
pan-application:: paloalto target only. Specify applications for the
security policy which can be predefined applications
(https://applipedia.paloaltonetworks.com/) and custom application
objects.
Security Policy Service Setting
When no protocol is specified in the term, the service will be
application-default.
When protocol is tcp or udp, and no source-port or
destination-port is specified, the service will be custom service
objects for the protocols and all ports (0-65535).
When protocol is tcp or udp, and a source-port or destination-port
is specified, the service will be custom service objects for the
protocols and ports.
pan-application can only be used when no protocol is specified in
the term, or the protocols tcp and udp.
=> Define and document behavior for pan-application usage.

capirca/lib/aclgenerator.py, capirca/lib/cisco.py, capirca/lib/juniper.py, capirca/lib/policy.py, doc/generators/cisco.md, doc/generators/juniper.md, policies/pol/sample_juniper_loopback.pol, tests/lib/arista_test.py, tests/lib/brocade_test.py, tests/lib/cisco_test.py, tests/lib/cisconx_test.py, tests/lib/ciscoxr_test.py, tests/lib/juniper_test.py, tests/lib/srxlo_test.py
See issue #245.
To be merged after https://github.com/google/capirca/pull/266
Especially when using mixed target, it is useful to be able to skip a given term for an AF.
Final result, on Juniper:
```
header {
comment:: "Sample Juniper lookback filter"
target:: juniper loopback mixed
}
term one {
source-address:: BOGON
address-family:: inet
protocol:: tcp
action:: accept
}
term two {
source-address:: BOGON
address-family:: inet6
protocol:: udp
action:: accept
}
term three {
source-address:: BOGON
protocol:: gre
action:: accept
}
```
Outputs:
```
firewall {
family inet {
/*
** $Id:$
** $Date:$
** $Revision:$
**
** Sample Juniper lookback filter
*/
replace: filter loopback4 {
interface-specific;
term one {
from {
source-address {
0.0.0.0/8;
192.0.0.0/24;
192.0.2.0/24;
198.18.0.0/15; …
```
=> Implement address_family token for Juniper and Cisco

requirements.txt, setup.py
It seems like Capirca targets Python 3.6+. The ipaddress library is
available natively beginning with Python 3.3+, or having it listed under
the project requirements pulls the PyPI library which hasn't seen
a release in almost 3 years and has a number of security issues:
- https://cwe.mitre.org/data/definitions/327.html
- https://www.cve.org/CVERecord?id=CVE-2021-29921
- https://www.cve.org/CVERecord?id=CVE-2020-14422
=> Remove ipaddress unnecessary dependency

capirca/lib/juniper.py, capirca/lib/policy.py, capirca/lib/policy_simple.py, capirca/lib/srxlo.py, tests/lib/juniper_test.py, tests/lib/policy_test.py
This adds support for `decapsulate` actions on Juniper, for example `decapsulate mpls-in-udp` which is available on (at least some) MXes and QFXes.
Trying to figure out if CLA is already in place, opening this already to gather feedback :-)
=> Add support for 'decapsulate' on Juniper platforms

capirca/lib/nsxt.py, requirements.txt, tests/lib/nsxt_test.py
Ability to run checked mainly by running `docker build --tag=capirca .` and `docker run capirca`, since the current `Dockerfile` conveniently uses Python 3.6.
To run the tests, a separate `Dockerfile.tests` was used (but not submitted) with the following changes:
WORKDIR /app
ENTRYPOINT ["python3", "-m", "unittest", "discover", "-s", ".", "-p", "nsxt_test.py", "-v"]
and running the test as follows:
docker build -f Dockerfile.tests --tag capirca:test_nsxt .
docker run capirca:test_nsxt
Fixes #345.
=> nsxt: Typing fixes for Python 3.6 compatibility.

.github/workflows/docker.yml, .github/workflows/main.yml, .github/workflows/pypi_release.yml, .github/workflows/windows.yml
This updates actions to:
* `actions/checkout@v4`
* `actions/setup-python@v5`
* `actions/setup-node@v4`
* `actions/upload-artifact@v4`
* `microsoft/setup-msbuild@v1.3.3`
This is because of the following error which we have been receiving in the CI:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
This does not attempt to fix the pre-existing build issues caused by typing problems introduced in other commits.
=> workflows: Upgrade actions to latest versions.
